### ISSUE TITLE
Pre Build Issue

### ISSUE THREAD

**Issue by kichappa** [cloudflare/python-worker-hello-world#4]
In the instructions before pre build, there is 
```source env/bin/activate```

But, what is `source`?

I get this error when I type it in my command line:
```
source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ source env/bin/activate
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by jclee** [comment]
It looks like the current instructions are specific to Linux or macOS, because "source" is a builtin command on unix shells that interprets the given file.  From your error message, it seems you are running PowerShell, which needs a different command to activate the virtualenv environment.  According to the following StackOverflow page, I guess you might need to run `env/bin/activate.ps1` instead?

https://stackoverflow.com/questions/1365081/virtualenv-in-powershell

**Comment by kichappa** [comment]
@jclee 

Thanks, solved!
